### ISSUE TITLE
kodi kypton

### ISSUE THREAD

**Issue by ghost** [wrxtasy/LibreELEC.tv.7.0#2]
first thanx for all your hard work! Is there any timeline regarding kodi krypton fro odroid (C2)?
I did some changes in inputstream dash addons, and so many new addons are currently set up on top of this....

**Comment by wrxtasy** [comment]
I'm a bit time poor lately, so have not had much of a chance to look seriously at Krypton.
Maybe this coming month.

I have seen some of your commits recently for AML in the XBMC Master, so feel a bit motivated to do something !

**Comment by ghost** [comment]
thx, i have it currently running with some initial help from milhouse.
Not 100% satisfied with video sync so far (23.7 fps) - but its runing.

Will push the changes to the official libreelec tree...
